### ISSUE TITLE
Wrong Harvard citation style

### ISSUE THREAD

**Issue by primoz-svetek** [seboettg/citeproc-php#81] opened 2020-03-26 17:34 UTC
# Please follow the general troubleshooting steps first:

- [ x] I read the README and followed the instructions.
- [ x] I am sure that the used CSL metadata follows the [CSL schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json).
- [ x] I use a valid CSL stylesheet

### Bug reports:
I am using OJS that uses Cite-Prop. In the Harvard Citation style the authors’ names are like , e.g. KenarN., without space between the surname and first letter of the name. I have been told that is wrong and there should be space in between.

Do you know if that is correct or wrong? Can you please let me know how to fix this?

#### Used CSL metadata ####

[harvard-cite-them-right.zip](https://github.com/seboettg/citeproc-php/files/4391963/harvard-cite-them-right.zip)

**Comment by seboettg** [comment] 2020-03-31 16:15
Hi @primoz-svetek!
please check if this issue is solved with the latest commit https://github.com/seboettg/citeproc-php/commit/6258cd9c49264a5bc1b357211a5c670b7da9d937
Thank you in advance!

**Comment by seboettg** [comment] 2020-04-04 16:57
Hi @primoz-svetek!
Version 2.2.0 has been released. Please update citeproc-php and check if the issue is solved. If yes, please close this ticket.

**Closed** 2020-04-27 20:52 UTC
